# Generated by Django 5.1.1 on 2024-11-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NinerCreations', '0004_activity_post_alter_activity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NinerCreations.comment'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
