# Generated by Django 5.1.1 on 2024-11-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NinerCreations', '0005_activity_comment_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
