# Generated by Django 5.1 on 2024-11-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NinerCreations', '0002_alter_comment_author'),
        ('NinerCreations', '0006_remove_activity_room_delete_room'),
    ]

    operations = [
    ]
