# Generated by Django 5.1.1 on 2024-11-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NinerCreations', '0009_post_members'),
        ('NinerCreations', '0009_project'),
    ]

    operations = [
    ]
