# Generated by Django 5.1.1 on 2024-11-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NinerCreations', '0009_project'),
        ('NinerCreations', '0011_alter_profile_bio'),
    ]

    operations = [
    ]
