# Generated by Django 5.1 on 2024-12-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NinerCreations', '0011_post_privacy'),
        ('NinerCreations', '0016_alter_profile_profile_picture'),
    ]

    operations = [
    ]
