# Generated by Django 5.1 on 2024-12-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NinerCreations', '0017_merge_20241202_1325'),
        ('NinerCreations', '0017_merge_20241202_1337'),
    ]

    operations = [
    ]
